---
title: About Me
output: 
  html_document:
    toc: true
    toc_float: true
---

Welcome to my `About Me` page! Below, you will find information about my research, teaching, advising, and a copy of my CV. 

# Research 

My research investigates the psychology of statistics. That is, what does it mean to do statistics, and how does one learn to do this? 

My primary research interests draw on theories and methods from the cognitive and learning sciences to investigate various aspects of statistical thinking. My theoretical research and my classroom-based research intertwine in my desire to develop a holistic social cognitive theory of statistical thinking. Specifically, I work towards radically reimagining how statistics is taught, in terms of both *what* is taught and *how* it is taught. 

<!--  To read more about my research during this time period, download a copy of my research statement from 2022 [here](https://github.com/RaoVNV/RaoVNV.github.io/raw/main/RaoVNV_Research.pdf). -->

# Teaching

आचार्यात् पादमादत्ते पादं शिष्यः स्वमेधया। सब्रह्मचारिभ्यः पादं पादं कालक्रमेण च॥ *Mahabharata 5:44:9*

This saying states that a student’s learning is derived from four sources: their teacher, themselves, their peers, and through time. These four sources do not operate independently - my choices as a teacher are inexorably intertwined with the impact each source has on students. 

My goal is thus to support my students’ learning by facilitating a learning environment in which all sources can contribute to students’ growth. To manifest these values in a learning environment, I adopt a student-centered approach to guide my student interactions and classroom presence. 

To read more about my teaching, download a copy of my teaching statement from 2022 [here](https://github.com/RaoVNV/RaoVNV.github.io/raw/main/RaoVNV_Teaching.pdf).

# Values

நான் யார்? [naan yaar] In Tamil, this question famously asked by the Saint Sri Ramana Maharishi simply asks, “Who am I?”. Together with the answer from the Yajur Veda, अहम् ब्रह्मास्मि [aham brahmaasmi], “I am Brahman”, this question fuels my drive to try to see myself in everything and everyone, and share my knowledge to help my students realize their immense potential. 

To read more about the way my values influence my research, teaching, and advising, download a copy of my EDI statement from 2022 [here](https://github.com/RaoVNV/RaoVNV.github.io/raw/main/RaoVNV_EDI_2pg.pdf).

# Advising

I believe my role as an advisor is to unlock the potential within each of my advisees. There are four dimensions along which I seek to support and mentor advisees, which I call the ABCDs of becoming a scholar. A scholar must be **a**utodidactic, **b**elieve in themselves, be **c**urious, and be **d**riven. 

<!-- 
A scholar must: 

- be an **A**utodidact. One must love learning. This requires one to seek out information and spend the necessary time reflecting upon and processing this information to help gain new insights. 
- **B**elieve in themselves. To generate new insights and new knowledge requires developing an idea that no one has had before. Others may not see the value in your ideas, but this should never be a deterrent. You must believe in yourself and pursue your ideas without hesitation. Whether or not others adopt your ideas is up to them -- your duty as a scholar is to show them new possibilities. 
- be **C**urious. All scholarship starts with curiosity, and asking a question such as `I wonder what's going on here?` or `I wonder why this happens?`. A scholar needs to have a keen and curious eye in order to generate new knowledge that can help explain the universe and human existence. 
- be **D**riven. The path to generating and spreading new knowledge is fraught with difficulty. To be a scholar, you have to dedicate yourself to a life of learning, knowledge, and the spread of knowledge. This means that no matter what obstacles emerge, you have to be driven to overcome them. 
-->

As an advisor, I share my experiences along these four dimensions with my advisees, and show them how I enact the process of scholarship. I invite them to do the same, and help to mentor them in learning what they love, developing self-confidence, noticing curious intricacies, and driving towards new knowledge. 

#### Are you a student interested in working with me? 

There are two types of research mentees I take: 

- RAs to work on my projects, whom I typically pay through grants
- Mentees to work on research questions of their own choice, who register for independent study credits

For more information, please visit my [advising](https://raovnv.github.io/advising) page. 

# Curriculum Vitae

Last Update: April 2025

To download a copy of my CV, click [here](https://github.com/RaoVNV/RaoVNV.github.io/raw/main/RaoVNV_CV.pdf).

<embed 
  src="/RaoVNV_CV.pdf" 
  type="application/pdf" 
  width="100%" 
  height="700px"
/>
