---
title: Education
output: 
  html_document:
    toc: true
    toc_float: true
---

Welcome to my education page! Below, you will find more information about each of the programs of study I have undertaken, and the advisors I have worked with.

# PhD in Educational Psychology 

Program: Quantitative Methods in Education // Concentration: Statistics Education

Start Date: Sep 2018
Expected Completion: May 2023

After being asked to redesign an introductory statistics course (GWU HSCI 2117; see my [teaching](/teaching.html/) for more), I sought to make evidence-based decisions and thus began searching the statistics education literature. This search quickly led me to [Dr. Joan Garfield](https://www.cehd.umn.edu/edpsych/people/jbg/), [Dr. Robert delMas](https://www.cehd.umn.edu/edpsych/people/delma001/) (Bob), and [Dr. Andrew Zieffler](https://www.cehd.umn.edu/edpsych/people/zief0002/) (Andy) at the University of Minnesota. After meeting Bob, Andy, and some of their current and former students during a visit to Minneapolis, I decided to study [statistics education](https://www.cehd.umn.edu/topics/statistics-education/) under their direction. 

My early milestone work focused on psychometric analyses of the Comprehensive Assessment of Outcomes in Statistics (CAOS). I then shifted to studying students' statistical thinking for my dissertation, especially their understanding of hypothesized data generating processes' production of sampling distributions in statistical testing. 

<!-- add links to CAOS and narrative project pages -->

# MA in Educational Psychology

Program: Psychological Foundations of Education // Concentration: Learning and Cognition

Start Date: Sep 2021
Expected Completion: May 2023

While earning my PhD, I began taking courses from faculty in the [Psychological Foundations of Education](https://www.cehd.umn.edu/edpsych/programs/foundations/) program in the [Department of Educational Psychology](https://www.cehd.umn.edu/edpsych/), focusing on courses such as Mathematical Cognition, Computational Thinking, and Advanced Cognition. 

I soon began working with Dr. Sashank Varma and [Dr. Jeffery Bye](https://www.cehd.umn.edu/people/jbye/) on projects related to the intersection of cognitive science and statistics education. I also begain working with [Dr. David DeLiema](https://www.cehd.umn.edu/edpsych/people/ddeliema/) on projects related to the intersection of learning sciences and statistics education (see my [research](https://raovnv.github.io/research.html) for more). To improve my knowledge and skills in the cognitive and learning sciences, I began formal study under the direction of [Dr. David DeLiema](https://www.cehd.umn.edu/edpsych/people/ddeliema/) and [Dr. Jeffery Bye](https://www.cehd.umn.edu/people/jbye/). 

<!-- The topic of my masters paper explored the cognitive foundations of probability underlying statistical reasoning and thinking. -->

# MS in Statistics

Degree date: Dec 2013

While working for the [US Census Bureau](https://www.census.gov/), I pursued an [MS in Statistics](https://statistics.columbian.gwu.edu/ms-statistics) from the [George Washington University](https://www.gwu.edu/) as a part-time student. My coursework primarily focused on modern data analysis and applied statistics, featuring courses such as Data Mining, Legal Statistics, and Modern Theory of Sample Surveys. 

I worked on some small projects with [Dr. Joseph L.  Gastwirth](https://home.gwu.edu/~jlgast/) and [Dr. Rida Moustafa](https://www.linkedin.com/in/rida-moustafa-a663971a7/), but due to competing priorities from my job (and given that I was not, at that time, considering an academic career), I never presented this work at conferences or produced manuscripts. 

# BS in Mathematics

Degree date: Dec 2008

Concentration: Pure Mathematics // Second Major: Economics // Minor: Spanish

Upon graduating high school I had no idea what I wanted to do for a career, but I always loved numbers and mathematics came easy, so I figured I'd major in mathematics. I soon fell in love with it, after taking a course in the Introduction to Mathematical Logic. I particularly loved taking Abstract Algebra and Number Theory. Along the way I also picked up a double major in Economics, spent some time as pre-med (and obtained an EMT-B and CPR Instructor license along the way), and also minored in Spanish (and spent a summer in Granada, Spain). 

As I neared graduation, I still was uncertain what I wanted for a career. I took the LSAT and applied to law schools, I took the GRE and the GRE Math subject test and applied for PhD programs in Mathematics as well as some in Economics, and I also started applying for jobs. I eventually received an offer to work for the US Census Bureau and decided to try working for a little before committing to graduate school. 

