---
title: "Data-to-Graphs and Back: Project Page"
---

# Project Team

In alphabetical order: 

- Andrew Zieffler
- Chelsey Legacy
- Jonathan M. Brown
- Robert delMas
- V.N. Vimal Rao

# Introduction to the Project

The 21st century world is one inundated with data. Everything from policy decisions to political strategies to advanced science to leisure pursuits such as streaming options are all based on data driven decisions. While complex analytics may be driving these processes, visualizations have proliferated throughout every day life as a new standard for individuals to consume information. From sports broadcasts to instagram pages about the Bachelor, modern data visualizations appear to be a mainstay for the coming years. 

Accordingly, statistics and data science curricula are adapting to teach students how to critically consume these modern data visualizations and also how to produce them. Yet the job of the teacher is no trivial thing. Teachers must not only consider how to teach (pedagogy), but also know what to teach (content), and be skilled in technology. This technical pedagogical content knowledge (TPCK) takes training and practice. 

To help inform the ways in which researchers can support teachers as they deliver modern data science curricula that include complex visualizations, this project investigates teachers' reasoning about the relationships between modern visualizations and their underlying data structures. 

# Initial Study

In the summer of 2020, we planned a series of activities to elicit participants' reasoning about the relationships between data structures and visualizations.

In the Fall of 2020 and again in the Spring of 2021, we recruited current high school statistics teachers from the University of Minnesota's [College in the Schools](https://ccaps.umn.edu/college-in-the-schools) program to complete a series of small group activities.

# Data-to-Graphs and Back @ IASE 2021

We presented our first analyses and results of this data at the [IASE 2021 Satellite Conference](https://iase-web.org/conference/satellite21/). Our results are summarized in our poster as well as our poster abstract, which can be viewed via the following links: 

[IASE 2021 Poster](https://github.com/RaoVNV/Data-to-Graphs/blob/main/iase-2021-poster.pdf)
<br>
[IASE 2021 Poster Abstract](https://github.com/RaoVNV/Data-to-Graphs/blob/main/IASE-2021-Final-Abstract.pdf) 


# Upcoming Paper in Preparation

We are currently working on a manuscript that will present the results of our project in more detail. Stay tuned!



