---
title: Research and Scholarship
output: 
  html_document:
    toc: true
    toc_float: true
---
<!--
Welcome to my research and scholarship page! Below, you will find information on my interests, links to project pages for my work, and my research values. 
-->

Welcome to my `Research and Scholarship` page! Below, you will find links to project pages for some of my projects. 

*Note: to return to this site from any of the project pages, click on my name listed under project team.*

<br>

# Interests

My work applies theories and methods from the cognitive and learning sciences to investigate the act of learning and doing statistics, and critically examines statistics education research theories and methodologies. 

Generally speaking, my work falls into one of three categories: 

- investigations of the cognitive processes underlying statistical thinking, 
- psychometric studies of the assessment of cognitive and non-cognitive characteristics related to learning and doing statistics, and
- design-based educational research to develop new statistics pedagogies. 

In my own projects, or when working with others, I seek to be a part of interdisciplinary teams founded on mutual curiosity and passion -- *"I cannot imagine being a sole researcher on any project or keeping ideas to myself" (Garfield, 2013, p. 6)*^[Garfield, J. (2013). Cooperative learning revisited: From an instructional method to a way of life. *Journal of Statistics Education, 21*(2).]. 

<br> 

# Active Projects

### Harnessing AI to Develop Students' Statistical Thinking

AI tools are here to stay. How do they change the way statistics can be practiced and taught? How do we ensure AI drives students' learning of statistics, as opposed to being used as a crutch to circumvent the development of statistical thinking skills? For more, visit [link coming soon](). 

### Authentic Statistical Graphical Literacy

However, graphs we see in our every day lives are often quite different than the graphs students are exposed to in introductory statistics courses. Can students interpret what *authentic* graphs they may see in their every days do and do not reveal? How we can measure their skills in doing so? How to support the development of these skills? For more, visit [RaoVNV.github.io/authenticliteracy/](/authenticliteracy/).

### Accepting Uncertainty

Statistics is not a set of this-or-that rules. It is all about uncertainty and variability. A key component of statistical thinking is to accept this inherent uncertainty. How ready are students to do this? How accepting of uncertainty to they walk out of statistics classes? Are students' views about statistics consistent with statisticians' views? For more, visit [RaoVNV.github.io/acceptuncertainty](/acceptuncertainty/).


<br>

# Ongoing Projects

### Categorization of Statistical Measures

How do the *statistically significant* and *not statistically significant* category labels affect our cognition of statistical measures like *p*-values and Cohen's *d* effect sizes? For more, visit [RaoVNV.github.io/p-values/](/p-values/).

### Human Clustering

How do humans cluster sets of points? Is their clustering reliable? What individual and group differences are there in human clustering? What other cognitive processes is clustering related to? For more, visit [RaoVNV.github.io/clustering/](/clustering/).

<!--

### Aesthetic Mappings

How do secondary teachers reason about aesthetic mappings linking complex data structures and modern data visualizations? For more, visit [RaoVNV.github.io/Data-to-Graphs/](/Data-to-Graphs/). 

<br>

### Biostatistical Literacy

What is biostatistical literacy, and how can we promote students' biostatistical literacy skills? For more, visit [RaoVNV.github.io/BiostatLiteracyProject](/BiostatLiteracyProject/).

<br>

### Gender Inclusivity

How should we incorporate and discuss gender as an attribute in datasets used in instruction and practice in STEM courses? For more, visit [https://raovnv.github.io/GenderInclusivity/](/GenderInclusivity/).

<br>

### Vedic Inspired Pedagogies

The Vedas and BhagavadGita contain essential lessons for all humanity. How can we borrow and apply pedagogical strategies from these timeless works to any subject we teach, including statistics? For more, visit [link coming soon]().



## Social Justice in Statistics

How can instructors incorporate social justice initiatives into statistics and data science classes? For more, visit [RaoVNV.github.io/SJinStats/](/SJinStats/). 

## Context in Statistics

How should instructors navigate context in statistics classes? For more, visit [RaoVNV.github.io/Contexts/](/Contexts/). 


# Values

## Scholarship

A major influence in my development as a researcher and scholar was a book discussing four models of scholarship beyond so-called traditional research^[Boyer, E. L. (1990). *Scholarship reconsidered: Priorities of the professoriate.* Princeton University Press: Lawrenceville, NJ.]. 

My own take on Boyer's ideas is that I want my research to incorporate both theory-generation as well as theory-application. Furthermore, as a statistics education professional, I want my work to include resources to support anyone who wants to use statistical tools, including researchers in other fields. 

While one may consider research as the generation of new knowledge, I do not hold knowledge as the ultimate prize. Whether or not the theory of gravity is true, it is *empowering* -- we can board an airplane and fly around the world. I want my work to be empowering, and as my focus is on statistics education, I want to empower individuals to be able to use statistics.

## Collaboration

My work heavily relies on interdisciplinary collaboration. As Dr. Joan Garfield once said, "I cannot imagine being a sole researcher on any project or keeping ideas to myself" (Garfield, 2013, p. 6)^[Garfield, J. (2013). Cooperative learning revisited: From an instructional method to a way of life. *Journal of Statistics Education, 21*(2).]. To wit, I founded a graduate student organizing called The Link Tank, whose aim is to connect people and ideas (find out more at [z.umn.edu/TheLinkTank](https://z.umn.edu/thelinktank)). You can also read more about my approach to research and scholarship in an article I wrote for SPARK magazine ('[From Happy Hour to Co-Author: How I Found an Academic Home](https://sparkezine.com/2021/04/04/from-happy-hour-to-co-author-how-i-found-an-academic-home/)'). 
-->

