---
title: V.N. Vimal Rao Work Experience
output: html_document
---

Welcome to my work experience page! Below, you will find details about each of the full time jobs I've held. 

# Chief of Data Management and Analysis

HIV/AIDS Bureau, Health Resources and Services Administration --
July 12, 2015 to Dec 27, 2016

I served as an innovative leader in data management and analysis. I supervised team of 8 FTEs and 2 interns in the provision of consultation, advice, and leadership for data collection, data processing and quality evaluations, advanced database management, and data analysis and dissemination. Voluntary separation. Final performance management appraisal program (PMAP) rating of ‘Achieved Outstanding Results’.

Main Duties:

- Supervise the collection of programmatic data for the Ryan White HIV/AIDS Program via the Ryan White Services Report, AIDS Drug Assistance Program Data Report, Dental Reimbursement Program, Community Based Dental Partnership Program, AIDS Education and Training Center Data Report, as well as programmatic grant allocation and expenditure reports
- Manage contracts with an approximate annual budget of $6 Million to assist in the development and implementation of data collection systems and processes on behalf of the HIV/AIDS Bureau
- Advise and brief senior bureau and agency leaders on issues related to the collection or analysis or Ryan White HIV/AIDS Program data
- Serve as senior statistician within the bureau and provide statistical reviews and consultation for the application of quantitative methodologies in research projects and other analyses related to the application of Ryan White HIV/AIDS Program data to public health or epidemiological studies
- Collaborate with other departmental agencies such as the Centers for Disease Control and Prevention, National Institutes of Health, and other bureaus within the Health Resources and Services Administration such as the Bureau of Primary Health Care and the Office of Policy Evaluation and Analysis on the collection and analysis of Ryan White HIV/AIDS Program data in conjunction with other health care data to impact matters related to HIV across the country

Selected Accomplishments:

- When I assumed the position of branch chief, the Division of Policy and Data had no staff with knowledge of data visualizations. I encouraged and mentored staff in the development of data visualization skills, and hired two interns to supplement our knowledge. I lead the interns and two statisticians in the creation of new and informative data visualizations utilizing for the first time Ryan White Services Report Data. Under this leadership, several data visualizations and graphics have been included as part of dissemination products to the public, for internal use only, for briefings of senior department officials, and for sharing with our stakeholders, to help supplement the story of the achievement of the Ryan White HIV/AIDS Program.
- The Ryan White Services Report is a new data set that the HIV/AIDS Bureau has only had for a few years. As the senior statistician in the HIV/AIDS Bureau, I have lead a team of mixed-scientific background including epidemiologists, biostatisticians, economists, nurses, and doctors, in the complex analysis of the Ryan White Services Report Data. This has included creative application of methods to analyze clinical outcomes and disparity analyses with adjustments for patient-factors and service provider-factors, creation of service provider performance benchmarks and goals, and other exploratory methods such as spatial statistics and association mining.
- During the 2014 calendar year, the time lag between data collection and the publication of base analysis files and dissemination of data products was approximately 14 months for the Ryan White Services Report and the AIDS Drug Assistance Program Data Report. Under my leadership, I set aggressive goals and motivated the data management branch to reduce the time lag from 14 months in 2014 to approximately 9 months in 2015 and 4 months in 2016 by developing essential staff skills, championing the use of efficient database technologies, emphasizing the writing and maintenance of computer code that can be re-usable and generalized, effecting good project management practices and the development of master project schedules and requirements documents. This phenomenal improvement has allowed all data products to be disseminated on a more timely schedule.

# Health Statistician

HIV/AIDS Bureau, Health Resources and Services Administration --
January 26, 2014 to July 11, 2015

I served as an Expert Statistician, Data Analyst, and SAS programmer. I provided statistical and epidemiological consultation, advice, and leadership for data collection, data processing and quality evaluations, advanced database management, and data analysis and dissemination. Separation due to promotion.

Main Duties:

- Design and manage statistical data systems with large databases including data cleaning and processing, data management and storage, preparation of standard reports, and data analysis
- Advise senior managers on the statistical design and implementation of operational research and program evaluation projects related to HIV/AIDS programs
- Provide expert advice, conceptual and technical guidance, and leadership in the application of statistical theories and methodologies to public health and epidemiological program data
- Use statistical software (SAS, SPSS, R, etc.) and data management software (Microsoft SQL Server, etc.) to manipulate, interpret, and analyse large and complex data sets
- Prepare slides, handouts, notes, and other professional documents as requested by Bureau managers, containing summaries of data analysis, relevant data limitations, and other statistical and quantitative insights
- Review contractual documents and work plans and products of contractors to ensure that they meet the Bureau’s statistical and data needs, and advise senior managers on the effective and efficient use of contractors to accomplish the Bureau’s statistical and data goals
- Coordinate statistical activities and deliverables across multiple program projects

Selected Accomplishments:

- Served as statistical reviewer for research studies in health services and infectious diseases and provided expert statistical consultation to bureau staff, ensuring appropriateness of statistical methods and techniques used, reviewing inherent analytic and data limitations, verifying the validity of conclusions based on statistical and quantitative evaluations, and providing guidance on the use and interpretation of data analysis methods and statistical tests
- Formed strategic partnerships and relationships with government agencies and private organizations, generating increased interest in the Bureau’s new client-level public health databases and data products, increasing Bureau visibility and customer requests for data
- Coached and trained branch staff, developing staff skills in using SAS software, SQL programming, and knowledge of general statistical theories, tools, and methods, to enable the branch to better meet customer needs and improve branch customer service performance

# Mathematical Statistician

Decennial Statistical Studies Division, US Census Bureau --
September 26, 2010 to January 25, 2014

I served as an expert in Statistical Quality Assurance and Acceptance Sampling. I managed and led quality assurance activities including research and development, program planning, instrument development and testing, operations management, and data analysis and reporting. Separation due to promotion.

Main Duties:

- Apply statistical quality assurance theory and methods to decennial census operations in order to ensure high levels of data integrity and data quality in data collection activities
- Represent the Division and Branch on Bureau workgroups and research teams, lead evaluations of current statistical and program practices and standards in quality assurance, and lead and perform methodological research to develop innovative strategies and processes for address listing quality assurance sampling including simulation studies when applicable
- Contribute to the development of quality assurance standards, and ensure Bureau practices comply with program policies, and government and industry statistical standards
- Perform statistical analysis of large census quality assurance databases and datasets, including Printing Quality Assurance, Census Follow-Up and Telephone Questionnaire Assistance Monitoring, Address Canvassing Quality Assurance, and others as required
- Author Quality Assurance Operations Plans, Statistical Analysis Plans, and Operational and Analytical Reports for Quality Control and Quality Assurance Activities
- Oversee and maintain the Demographic Area Address Listing Check Database and Sampling System, performing necessary updates and changes to methodologies as required, and resolving high complexity problems with existing data management systems

Selected Accomplishments:

- Provided expert statistical consultations to Bureau geographers and their partners in the US Geological Survey, including advising on the appropriateness and value of possible experimental designs and methods, designing custom geographical studies, creating complex sample survey designs, performing data analysis and estimation on data collected from these studies, and assisting in preparing presentations and journal articles on study findings
- Redesigned address listing quality assurance programs to achieve higher efficiency use of resources, including developing survey instruments, writing field staff manuals and procedures, and designing statistical sampling systems, data systems and database management, and data analysis and reporting systems, leading to an estimated 50% reduction in data errors without incurring any additional costs
- Led staff and colleagues towards creativity and innovation in statistical quality control methodology, specifically leading innovations in the use of model-based sampling with bayesian updating, advanced acceptance sampling methods, evaluation of programs via simulation studies, development of interactive user interfaces, and new workflow management practices
- Contributed to the re-writing of Quality Statistics standards for ASTM on statistical sampling, quality assurance sampling, quality assurance testing, and statistical analysis, and served on the Committee for Quality and Statistics as a representative of the Census Bureau


# Mathematical Statistician

National Processing Center, US Census Bureau --
May 26, 2009 to September 25, 2010

I directly oversaw the Survey Reliability Unit (SRU) in performing operations in data integrity and quality control of data collection methodology for national surveys. Separation due to promotion.

Main Duties:

- Oversee all day-to-day operations of the SRU and all SRU supervisory statistical assistants, including coordinating administrative activities for all staff in the unit, analyzing available resources and make projections based on project needs, coordinating and planning efficient utilization of available resources to successfully complete multiple overlapping short-term projects, setting work assignments and priorities for staff to ensure adequate coverage, developing budget estimates and recommendations, managing operational project budgets, and planning and ensuring appropriate staffing levels
- Establish processes, protocols, and procedures for staff to follow on short-term projects, conduct special ad-hoc training to ensure staff knowledge and compliance, and ensure all procedures and practices adhere to recommended statistical standards and program and administrative requirements and needs
- Supervise staff in the SRU, including monitoring work quality, evaluation and review of staff performance, developing staff and encouraging professional training and personal growth, and building a cohesive team environment between staff, and work with EEO Specialists and Union Representatives in handling formal EEO or Union Complaints
- Coach, mentor, and support SRU supervisory statistical assistants in their management and oversight of all statistical assistants on their team, and support them in management activities
- Maintain strong unit morale and a healthy work environment by resolving disputes and conflicts in a timely and respectful manner using Alternative Dispute Resolution practices, counseling employees on appropriate conduct and behaviour, coaching employees to improve on-the-job performance, and counseling employees on their rights afforded by Collective Bargaining Agreements and the services the Bureau offers them

Selected Accomplishments: 

- Evaluated programs for inefficiencies in operations, and instituted improvements in processes and procedures, leading to increased accuracy of data for the maintenance of address based sampling frames, and increased staff efficiency, saving the Bureau approximately $250,000 in further data cleaning activities